#!/bin/bash
# Quick Reference - BIM Takeoff Website Commands

echo "🌐 BIM Takeoff Website - Quick Commands"
echo "========================================"
echo ""
echo "📝 DEPLOYMENT:"
echo "   ./deploy-bilingual.sh \"Your message\""
echo ""
echo "🔨 BUILD ONLY:"
echo "   English: quarto render"
echo "   Polish:  cd pl && quarto render && cd .."
echo ""
echo "🌍 URLS:"
echo "   🇬🇧 EN: https://robertkowalski1974.github.io/bimtakeoff-website/"
echo "   🇵🇱 PL: https://robertkowalski1974.github.io/bimtakeoff-website/pl/"
echo ""
echo "📁 EDIT FILES:"
echo "   English: index.qmd"
echo "   Polish:  pl/index.qmd"
echo ""
echo "⚙️  CONFIG:"
echo "   English: _quarto.yml"
echo "   Polish:  pl/_quarto.yml"
echo ""
echo "📚 DOCUMENTATION:"
echo "   Main:    POLISH_VERSION_COMPLETE.md"
echo "   Polish:  pl/README.md"
echo ""
