project:
  type: website
  output-dir: ../docs/pl

website:
  title: "BIM Takeoff"
  site-url: https://robertkowalski1974.github.io/bimtakeoff-website/pl
  description: "Kosztorysowanie BIM 5D | Przedmiary i Obmiary | 20 Lat Doświadczenia UK/Australia | Zgodność z KNR/KNNR i BIM 2030"
  favicon: ../images/favicon.ico
  
  navbar:
    background: "#2C2C2C"
    foreground: "#FFFFFF"
    logo: "../images/BIM TAKEOFF V2-2.jpg"
    logo-alt: "Logo BIM Takeoff"
    left:
      - text: "Strona Główna"
        href: index.qmd
      - text: "Usługi"
        menu:
          - text: "Kosztorysowanie i Planowanie Budżetu"
            href: coming-soon.qmd
          - text: "Specjalistyczne Usługi Branżowe"
            href: coming-soon.qmd
          - text: "Automatyczny Przedmiar z Modeli BIM"
            href: coming-soon.qmd
          - text: "Bieżąca Kontrola Kosztów"
            href: coming-soon.qmd
          - text: "Kosztorysowanie BREEAM/ESG"
            href: coming-soon.qmd
          - text: "Kosztorysowanie Instalacji MEP"
            href: coming-soon.qmd
          - text: "Analiza Wariantowa"
            href: coming-soon.qmd
          - text: "Kompleksowe Raportowanie"
            href: coming-soon.qmd
          - text: "Przygotowanie Ofert Przetargowych"
            href: coming-soon.qmd
          - text: "Tradycyjny Przedmiar z Rysunków 2D"
            href: coming-soon.qmd
          - text: "Zarządzanie Danymi BIM"
            href: coming-soon.qmd
          - text: "Logistyka Budowlana"
            href: coming-soon.qmd
      - text: "Branże"
        menu:
          - text: "Magazyny i Logistyka"
            href: coming-soon.qmd
          - text: "Centra Danych"
            href: coming-soon.qmd
          - text: "Deweloperstwo Mieszkaniowe"
            href: coming-soon.qmd
          - text: "Remediacja i Modernizacja"
            href: coming-soon.qmd
          - text: "Deweloperstwo Komercyjne"
            href: coming-soon.qmd
          - text: "Opieka Zdrowotna"
            href: coming-soon.qmd
          - text: "Przemysł i Produkcja"
            href: coming-soon.qmd
          - text: "Infrastruktura"
            href: coming-soon.qmd
      - text: "Portfolio"
        href: coming-soon.qmd
      - text: "Zasoby"
        menu:
          - text: "Przewodnik BIM 2030"
            href: coming-soon.qmd
          - text: "Kalkulator Oszczędności"
            href: coming-soon.qmd
          - text: "Studia Przypadków"
            href: coming-soon.qmd
      - text: "O Nas"
        href: coming-soon.qmd
      - text: "Kontakt"
        href: coming-soon.qmd
    right:
      - text: "PL"
        href: /pl/
      - text: "EN"
        href: /
    
  sidebar: false
  
  page-footer:
    background: "#2C2C2C"
    foreground: "#FFFFFF"
    left: |
      © 2025 BIM Takeoff. Wszelkie prawa zastrzeżone.<br>
      Kosztorysowanie BIM 5D | Certyfikacja RICS | Zgodność KNR/KNNR
    center: |
      **Informacje**<br>
      [Polityka Prywatności](coming-soon.qmd) | [Warunki Współpracy](coming-soon.qmd)
    right: |
      **Kontakt**<br>
      [info@bimtakeoff.com](mailto:info@bimtakeoff.com)<br>
      [+48 508 209 313](tel:+48508209313)

format:
  html:
    theme: 
      - cosmo
      - ../custom.scss
    css: 
      - ../css/styles.css
    toc: false
    page-layout: full
    smooth-scroll: true
    code-fold: false
    code-tools: false
    link-external-newwindow: true
    link-external-icon: false
    lang: pl
    include-in-header:
      text: |
        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-PLB9BH8W');</script>
        <!-- End Google Tag Manager -->
    include-after-body:
      - text: |
          <!-- Google Tag Manager (noscript) -->
          <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PLB9BH8W"
          height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
          <!-- End Google Tag Manager (noscript) -->
          <!-- Scroll Effects & Animations -->
          <script src="../js/scroll-effects.js"></script>
      - _polish-navbar-include.html
    
execute:
  freeze: auto
  echo: false
  warning: false
  message: false
