project:
  type: website
  output-dir: ../docs/pl

website:
  title: "BIM Takeoff"
  site-url: "https://robertkowalski1974.github.io/bimtakeoff-website/pl"
  description: "Kosztorysowanie BIM 5D | Przedmiary i Obmiary | 20 Lat Doświadczenia EU/UK/Australia | Zgodność z BIM 2030"
  favicon: ../images/favicon.ico
  
  # Open Graph metadata for social sharing (Polish)
  open-graph:
    locale: pl_PL
    site-name: "BIM Takeoff"
    image: "../images/BIM TAKEOFF V2-2.jpg"
  
  navbar:
    background: "#2C2C2C"
    foreground: "#FFFFFF"
    logo: "../images/BIM TAKEOFF V2-2.jpg"
    logo-alt: "Logo BIM Takeoff"
    left:
      - text: "Strona Główna"
        href: index.qmd
      - text: "Usługi"
        menu:
          - text: "Kosztorysowanie i Planowanie Budżetu"
            href: /pl/uslugi/kosztorysowanie-i-planowanie-budzetu.html
          - text: "Specjalistyczne Usługi Branżowe"
            href: coming-soon.qmd
          - text: "Automatyczny Przedmiar z Modeli BIM"
            href: coming-soon.qmd
          - text: "Bieżąca Kontrola Kosztów"
            href: coming-soon.qmd
          - text: "Kosztorysowanie BREEAM/ESG"
            href: coming-soon.qmd
          - text: "Kosztorysowanie Instalacji MEP"
            href: coming-soon.qmd
          - text: "Analiza Wariantowa"
            href: coming-soon.qmd
          - text: "Kompleksowe Raportowanie"
            href: coming-soon.qmd
          - text: "Przygotowanie Ofert Przetargowych"
            href: coming-soon.qmd
          - text: "Tradycyjny Przedmiar z Rysunków 2D"
            href: coming-soon.qmd
          - text: "Zarządzanie Danymi BIM"
            href: coming-soon.qmd
          - text: "Logistyka Budowlana"
            href: coming-soon.qmd
      - text: "Branże"
        menu:
          - text: "Magazyny i Logistyka"
            href: coming-soon.qmd
          - text: "Centra Danych"
            href: coming-soon.qmd
          - text: "Deweloperstwo Mieszkaniowe"
            href: coming-soon.qmd
          - text: "Remediacja i Modernizacja"
            href: coming-soon.qmd
          - text: "Deweloperstwo Komercyjne"
            href: coming-soon.qmd
          - text: "Opieka Zdrowotna"
            href: coming-soon.qmd
          - text: "Przemysł i Produkcja"
            href: coming-soon.qmd
          - text: "Infrastruktura"
            href: coming-soon.qmd
      - text: "Portfolio"
        href: coming-soon.qmd
      - text: "Zasoby"
        menu:
          - text: "Przewodnik BIM 2030"
            href: coming-soon.qmd
          - text: "Kalkulator Oszczędności"
            href: coming-soon.qmd
          - text: "Studia Przypadków"
            href: coming-soon.qmd
      - text: "Kontakt"
        href: kontakt.qmd
    right:
      - text: "PL"
        href: /pl/
      - text: "EN"
        href: /
    
  sidebar: false
  
  page-footer:
    background: "#2C2C2C"
    foreground: "#FFFFFF"
    left: |
      © 2025 BIM Takeoff. Wszelkie prawa zastrzeżone.<br>
      Kosztorysowanie BIM 5D | Certyfikacja RICS | Zgodność KNR/KNNR
    center: |
      **Informacje**<br>
      [Polityka Prywatności](coming-soon.qmd) | [Warunki Współpracy](coming-soon.qmd)
    right: |
      **Kontakt**<br>
      [info@bimtakeoff.com](mailto:info@bimtakeoff.com)<br>
      [+48 508 209 313](tel:+48508209313)

format:
  html:
    theme: 
      - cosmo
      - ../custom.scss
    css: 
      - ../css/styles.css
    toc: false
    page-layout: full
    smooth-scroll: true
    code-fold: false
    code-tools: false
    link-external-newwindow: true
    link-external-icon: false
    # Language declaration for Polish pages
    lang: pl
    include-in-header:
      text: |
        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-PLB9BH8W');</script>
        <!-- End Google Tag Manager -->
        
        <!-- Twitter Card metadata (Polish) -->
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="@bimtakeoff">
        <meta name="twitter:creator" content="@bimtakeoff">
        <meta name="twitter:title" content="BIM Takeoff - Profesjonalne Kosztorysowanie BIM 5D">
        <meta name="twitter:description" content="Kosztorysowanie BIM 5D | Przedmiary i Obmiary | 20 Lat Doświadczenia EU/UK/Australia">
        
        <!-- Organization Structured Data (Polish version) -->
        <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "ProfessionalService",
          "name": "BIM Takeoff",
          "alternateName": "BIM Takeoff Polska",
          "description": "Profesjonalne usługi kosztorysowania BIM 5D i przedmiarów budowlanych",
          "url": "https://robertkowalski1974.github.io/bimtakeoff-website/pl",
          "logo": "https://robertkowalski1974.github.io/bimtakeoff-website/images/BIM TAKEOFF V2-2.jpg",
          "image": "https://robertkowalski1974.github.io/bimtakeoff-website/images/BIM TAKEOFF V2-2.jpg",
          "telephone": "+48-508-209-313",
          "email": "info@bimtakeoff.com",
          "address": {
            "@type": "PostalAddress",
            "addressCountry": "PL"
          },
          "areaServed": [
            {
              "@type": "Country",
              "name": "Polska"
            },
            {
              "@type": "Country",
              "name": "United Kingdom"
            },
            {
              "@type": "Country",
              "name": "Australia"
            }
          ],
          "serviceType": [
            "Kosztorysowanie BIM 5D",
            "Przedmiar budowlany",
            "Obmiar budowlany",
            "Automatyczne przedmiarowanie",
            "Usługi kosztorysowe"
          ],
          "priceRange": "$$",
          "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": "5",
            "reviewCount": "20"
          },
          "knowsLanguage": [
            {
              "@type": "Language",
              "name": "Polski",
              "alternateName": "pl"
            },
            {
              "@type": "Language",
              "name": "English",
              "alternateName": "en"
            }
          ]
        }
        </script>
    include-after-body:
      - text: |
          <!-- Google Tag Manager (noscript) -->
          <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PLB9BH8W"
          height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
          <!-- End Google Tag Manager (noscript) -->
          <!-- Scroll Effects & Animations -->
          <script src="../js/scroll-effects.js"></script>
    
execute:
  freeze: auto
  echo: false
  warning: false
  message: false
