#!/bin/bash

# ===================================
# BILINGUAL WEBSITE - QUICK REFERENCE
# ===================================

echo "BIM Takeoff Bilingual Website - Quick Commands"
echo "=============================================="
echo ""
echo "1. TEST LOCALLY (Recommended first):"
echo "   ./test-bilingual.sh"
echo ""
echo "2. START PREVIEW SERVER:"
echo "   quarto preview"
echo "   Then open: http://localhost:XXXX/"
echo "   Click 'PL' button to test Polish version"
echo ""
echo "3. MANUAL RENDER:"
echo "   quarto render"
echo ""
echo "4. CLEAN BUILD:"
echo "   rm -rf docs/pl && quarto render"
echo ""
echo "5. DEPLOY TO GITHUB:"
echo "   git add -A"
echo "   git commit -m 'Update bilingual website'"
echo "   git push origin main"
echo ""
echo "6. VIEW DEBUG INFO:"
echo "   Open browser console (F12) on Polish pages"
echo "   Look for: [BilingualNav] messages"
echo ""
echo "=============================================="
echo ""
echo "FILES INVOLVED:"
echo "  - _quarto.yml (main config)"
echo "  - _navbar-translation-enhanced.html (translation script)"
echo "  - pl/ (Polish content directory)"
echo ""
echo "LIVE SITE:"
echo "  https://robertkowalski1974.github.io/bimtakeoff-website"
echo ""
