---
title: "ROI Analysis Report"
subtitle: "Professional Cost Estimation Services"
format:
  pdf:
    documentclass: article
    geometry:
      - top=20mm
      - bottom=20mm
      - left=20mm
      - right=20mm
    fontsize: 11pt
    colorlinks: true
    include-in-header:
      text: |
        \usepackage{xcolor}
        \definecolor{bimOrange}{RGB}{255,153,0}
        \definecolor{bimGreen}{RGB}{16,185,129}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{}
        \renewcommand{\headrulewidth}{0pt}
        \fancyfoot[C]{\color{gray}\small www.bimtakeoff.com | enquiry@bimtakeoff.com | +61 480 373 900}
---

```{r}
#| echo: false
#| warning: false

# This would read from localStorage via JavaScript
# For now, using example data

project_value <- 9400000
total_savings <- 909830
roi_percentage <- 1110
currency <- "EUR"
annual_savings <- total_savings * 3
```

\begin{center}
\colorbox{bimOrange!20}{\parbox{16cm}{
\centering
\Large\textbf{\color{bimOrange}WARTOŚĆ PROJEKTU}\\[0.5em]
\Huge\textbf{`r format(project_value, big.mark=" ")` `r currency`}
}}
\end{center}

\vspace{1em}

\begin{center}
\colorbox{bimGreen!20}{\parbox{16cm}{
\centering
\Large\textbf{\color{bimGreen}SZACOWANE OSZCZĘDNOŚCI}\\[0.5em]
\Huge\textbf{`r format(total_savings, big.mark=" ")` `r currency`}
}}
\end{center}

\vspace{1em}

\begin{center}
\colorbox{bimOrange!10}{\parbox{16cm}{
\centering
\Large\textbf{\color{bimOrange}ZWROT Z INWESTYCJI}\\[0.5em]
\Huge\textbf{`r roi_percentage`\%}
}}
\end{center}

\newpage

## Kluczowe Korzyści

\color{bimGreen}✓\color{black} 3-10 dni realizacji vs 6-8 tygodni tradycyjnie

\color{bimGreen}✓\color{black} Gwarantowana dokładność ±3-5%

\color{bimGreen}✓\color{black} Zgodność z BSR i wymogami prawnymi

\color{bimGreen}✓\color{black} 20+ lat międzynarodowego doświadczenia

\color{bimGreen}✓\color{black} 2000+ zrealizowanych projektów globalnie

## Analiza Wpływu Finansowego

| Obszar Redukcji Kosztów | Metoda Tradycyjna | Z BIM Takeoff | Oszczędności |
|-------------------------|-------------------|---------------|--------------|
| Czas Wyceny             | 6-8 tygodni       | 3-10 dni      | 75% redukcji |
| Dokładność              | ±10-15%           | ±3-5%         | 67% poprawa  |
| Koszty Poprawek         | 5-10% budżetu     | <2% budżetu   | 564 000 EUR  |
| Zmiany w Projekcie      | 15-20% typowo     | 5-8% typowo   | 1 128 000 EUR|

\vspace{2em}

\begin{center}
\colorbox{bimOrange!30}{\parbox{16cm}{
\centering
\LARGE\textbf{\color{bimOrange}TWOJE POTENCJALNE ROCZNE OSZCZĘDNOŚCI:}\\[0.5em]
\Huge\textbf{`r format(annual_savings, big.mark=" ")` `r currency`}
}}
\end{center}
